version: '3'

volumes:
  mysql:


services:
  crawler:
    build:
      context: .
      dockerfile: docker/crawler/Dockerfile
    depends_on:
      - mysql
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200k"
    env_file:
      - ./.env
    environment:
      MYSQL_HOST: "localhost"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/production/Dockerfile
    depends_on:
      - mysql
      - crawler
    ports:
      - "80:8000"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200k"
    env_file:
      - ./.env

  mysql:
    build:
      context: .
      dockerfile: docker/persistence/Dockerfile
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200k"
    env_file:
      - ./.env
